name: ANN-NSGA-II
channels:
  - conda-forge
  - defaults
dependencies:
  - ampl-asl=1.0.0=he0c23c2_2
  - aom=3.12.1=h00a0c3c_0
  - asttokens=3.0.0=py313haa95532_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - cloudpickle=3.1.2=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.3=py313haa95532_0
  - contourpy=1.3.3=py313h214f63a_0
  - cycler=0.12.1=py313haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py313h885b0b7_1
  - decorator=5.2.1=py313haa95532_0
  - executing=2.2.1=py313haa95532_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py313haa95532_0
  - fmt=12.0.0=h29169d4_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py313h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.10=h62dcd97_0
  - fsspec=2025.10.0=py313h4442805_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py313h8598115_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icu=73.1=h6c2663c_0
  - ipopt=3.14.19=h75e447d_1
  - ipykernel=6.31.0=py313h4442805_0
  - ipyparallel=9.0.2=py313haa95532_0
  - ipython=9.7.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=py313haa95532_1
  - jupyter_core=5.9.1=py313haa95532_0
  - kiwisolver=1.4.9=py313h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libavif=1.3.0=h5bd13ec_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libboost=1.88.0=h3d2b97d_0
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=20.1.8=default_hccbf073_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h56d1f94_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libllvm20=20.1.8=h3aa9ab2_0
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.1=h3a18249_0
  - libtorch=2.9.1=cpu_mkl_h59ad6ad_101
  - libuv=1.51.0=hfd05255_1
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib=3.10.8=py313hfa70ccb_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - matplotlib-inline=0.2.1=py313haa95532_0
  - mkl=2025.3.0=hac47afa_454
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py313haa95532_0
  - mumps-seq=5.8.1=hd297af6_4
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - nest-asyncio=1.6.0=py313haa95532_0
  - networkx=3.6.1=py313haa95532_0
  - nlopt=2.10.0=py313h434f71c_1
  - numpy=2.4.0=py313hce7ae62_0
  - openssl=3.0.18=h543e019_0
  - optree=0.18.0=py313h03f52e7_0
  - packaging=25.0=py313haa95532_1
  - pagmo=2.19.1=h8fe6d59_8
  - parso=0.8.5=py313haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py313h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313h02ab6af_1
  - pure_eval=0.2.3=py313haa95532_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pygments=2.19.2=py313haa95532_0
  - pygmo=2.19.7=py313h42beeac_7
  - pyparsing=3.2.5=py313haa95532_0
  - pyside6=6.9.2=py313h151a370_0
  - python=3.13.11=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python_abi=3.13=3_cp313
  - pytorch=2.9.1=cpu_mkl_py313_h4c75245_101
  - pywin32=311=py313h885b0b7_0
  - pyzmq=27.1.0=py313h7149c55_1
  - qhull=2020.2=h59b6b97_2
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hb1e082f_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2025.11.05=ha104f34_0
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sleef=3.9.0=h67fd636_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py313haa95532_0
  - sympy=1.14.0=py313haa95532_1
  - tbb=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py313h02ab6af_0
  - tqdm=4.67.1=py313h4442805_1
  - traitlets=5.14.3=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
    - scipy==1.16.3
prefix: C:\Users\chris\anaconda3\envs\pygmo
